#!/usr/bin/env make
WGET = wget -N -nv --show-progress -P

downloads_linux:
	wget -N -nv --show-progress http://tiddlywiki.com/empty.html -O tiddlywiki-empty.html
	$(WGET) http://downloads.lwks.com/lwks-12.6.0-amd64.deb
	$(WGET) https://github.com/jliljebl/flowblade/releases/download/1.12.2/flowblade-1.12.0-1_all.deb
	$(WGET) https://bitbucket.org/klembot/twinejs/downloads/twine_2.0.11_linux64.zip
	$(WGET) https://github.com/BurntSushi/xsv/releases/download/0.10.3/xsv-0.10.3-i686-unknown-linux-musl.tar.gz
	$(WGET) https://github.com/Dynalon/mdwiki/releases/download/0.6.2/mdwiki-0.6.2.zip
	$(WGET) https://github.com/feross/webtorrent-desktop/releases/download/v0.16.0/webtorrent-desktop_0.16.0-1_amd64.deb
	$(WGET) https://github.com/gbevin/SendMIDI/releases/download/1.0.5/sendmidi-linux-1.0.5.zip
	$(WGET) https://github.com/junegunn/fzf-bin/releases/download/0.15.9/fzf-0.15.9-linux_amd64.tgz
	$(WGET) https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Linux-64.tar.xz
	$(WGET) http://downloads.lwks.com/lwks-12.6.0-amd64.deb
	$(WGET) https://github.com/jliljebl/flowblade/releases/download/1.12.2/flowblade-1.12.0-1_all.deb
	$(WGET) https://bitbucket.org/klembot/twinejs/downloads/twine_2.0.11_linux64.zip
	$(WGET) https://github.com/BurntSushi/xsv/releases/download/0.10.3/xsv-0.10.3-i686-unknown-linux-musl.tar.gz
	$(WGET) https://github.com/Dynalon/mdwiki/releases/download/0.6.2/mdwiki-0.6.2.zip
	$(WGET) https://github.com/feross/webtorrent-desktop/releases/download/v0.16.0/webtorrent-desktop_0.16.0-1_amd64.deb
	$(WGET) https://github.com/gbevin/SendMIDI/releases/download/1.0.5/sendmidi-linux-1.0.5.zip
	$(WGET) https://github.com/junegunn/fzf-bin/releases/download/0.15.9/fzf-0.15.9-linux_amd64.tgz
	$(WGET) https://s3.amazonaws.com/Minecraft.Download/versions/1.11.2/minecraft_server.1.11.2.jar
	$(WGET) https://github.com/vrana/adminer/releases/download/v4.3.1/adminer-4.3.1.php
	$(WGET) http://iographica.com/download/linux/IOGraph_v1_0_1.jar
	$(WGET) https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-resolvers.csv
	$(WGET) http://ppa.launchpad.net/mank319/go-for-it/ubuntu/pool/main/g/go-for-it/go-for-it_1.4.7-0~142~ubuntu16.10.1_amd64.deb # https://github.com/mank319/Go-For-It (see PPA for other files)
	$(WGET) http://ppa.launchpad.net/gottcode/gcppa/ubuntu/pool/main/k/kapow/kapow_1.5.2-0ppa1~zesty1_amd64.deb # https://gottcode.org/kapow/ (see PPA for other files)
	$(WGET) http://ppa.launchpad.net/obsproject/obs-studio/ubuntu/pool/main/o/obs-studio/obs-studio_19.0.2-0obsproject1~zesty_amd64.deb # https://obsproject.com/ (see PPA for other files) #TODO add GPG keys for verification https://jgeboski.github.io/obs.key 
	$(WGET) https://github.com/dyson/indicator-workspaces/releases/download/v0.5/indicator-workspaces_0.5_all.deb # https://github.com/dyson/indicator-workspaces
	$(WGET) http://ppa.launchpad.net/tsbarnes/indicator-keylock/ubuntu/pool/main/i/indicator-keylock/indicator-keylock_3.0.2-0~ppa1_amd64.deb # https://launchpad.net/~tsbarnes/+archive/ubuntu/indicator-keylock (see PPA for other files)
	$(WGET) http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu/pool/main/s/sublime-text-installer/sublime-text-installer_3126-2~webupd8~1_all.deb # https://www.sublimetext.com/3 (non-free) (see PPA for other files)
	$(WGET) http://downloads.lwks.com/lwks-12.6.0-amd64.deb # https://www.lwks.com/ (non-free)
	$(WGET) http://ppa.launchpad.net/mapmap/mapmap/ubuntu/pool/main/m/mapmap/mapmap_0.4.0-1~trusty~ppa1_amd64.deb # http://mapmap.info/ (see PPA for other files)
	$(WGET) https://az764295.vo.msecnd.net/stable/ee428b0eead68bf0fb99ab5fdc4439be227b6281/code_1.8.1-1482158209_amd64.deb # https://code.visualstudio.com/ https://github.com/Microsoft/vscode
	$(WGET) https://github.com/brrd/Abricotine/releases/download/0.5.0/Abricotine-linux-ubuntu-debian-x64.deb # https://github.com/brrd/Abricotine
