#!/usr/bin/env make
WGET = wget -N -nv --show-progress -P
	
downloads_windows:
	$(WGET) WINDOWS/BINARIES/ http://23.98.147.40/uploads/MagicaVoxel-0.98.1-win-mac-beta.zip
	$(WGET) WINDOWS/BINARIES/ http://freealarmclocksoftware.com/FreeAlarmClockPortable.zip
	$(WGET) WINDOWS/BINARIES/ http://download.wsusoffline.net/wsusoffline1092.zip
	$(WGET) WINDOWS/BINARIES/ https://github.com/gbevin/SendMIDI/releases/download/1.0.5/sendmidi-windows-1.0.5.zip
	$(WGET) WINDOWS/ https://github.com/tim-lebedkov/npackd-cpp/releases/download/version_1.22.2/Npackd64-1.22.2.msi
	$(WGET) WINDOWS/ https://github.com/tim-lebedkov/npackd-cpp/releases/download/version_1.22.2/NpackdCL-1.22.2.msi
	#$(WGET) WINDOWS/BINARIES/ https://github.com/brrd/Abricotine/releases/download/0.5.0/Abricotine-setup-win32-x64.exe # https://github.com/brrd/Abricotine
	$(WGET) WINDOWS/BINARIES/ https://github.com/EionRobb/pidgin-opensteamworks/releases/download/1.6.1/libsteam-1.6.1.dll
